sudo: required

language: node_js

# services:
#   - docker

before_install:
# - docker pull node:alpine
# - docker run -d -p 80:3001 --expose 3001 -v $(pwd):/opt/app/ -w=/opt/app/  node:alpine /bin/sh -c "npm install && npm run dev"
# - docker ps -a
 - npm cache clean -f
 - npm install

script:
- npm run dev

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
