export const SET_PAGE = 'SET_PAGE';
export const SET_OVERLAY = 'SET_OVERLAY';
export const UNSET_OVERLAY = 'UNSET_OVERLAY';
export const SET_VALIDATION_MESSAGES = 'SET_VALIDATION_MESSAGES';
export const CLEAR_VALIDATION_MESSAGES = 'CLEAR_VALIDATION_MESSAGES';